services:
  rag:
    build: .
    image: terminal-rag:v1.0.0
    container_name: rag-cli
    volumes:
      - ./data:/app/data # 데이터(인덱스, 문서) 유지
      - ./.env:/app/.env # API Keys
    working_dir: /app
    # 사용자가 명령어를 오버라이드  수 있도록 함
    entrypoint: [ "python", "-m", "cli.main" ]
